<expr> := mymul(<expr>, <expr>) | mysub(<expr>, <expr>) | myadd(<expr>, <expr>) | pdiv(<expr>, <expr>) | if_cond(<expr>, <expr>, <expr>, <expr>) | (<expr>) | sin(<expr>) | cos(<expr>) | tan(<expr>) | exp(<expr>) | log(<expr>) | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i] | dim[<var>][i]
<var> := 0 | 1 | 2 | 3 | 4 | 5