<expr> := mymul(<expr>, <expr>) | mysub(<expr>, <expr>) | myadd(<expr>, <expr>) | pdiv(<expr>, <expr>) | if_cond(<expr>, <expr>, <expr>, <expr>) | (<expr>) | sin(<expr>) | cos(<expr>) | tan(<expr>) | exp(<expr>) | log(<expr>) | Dim[<var>][i]
<var> := 1<var1> | 2<var1> | 3<var1> | 4<var1> | 5<var1>
<var1> := 0 | 1 | 2 | 3 | 4 | 5 