<classifier>:=RandomForest(<n_estimators>, <random_state>) | SVM(<random_state>) | DecisionTree(<random_state>) | NB()
<n_estimators>:= 100 | 500 | 1000 | 1500 | 2000 | 2500 | 5000 | 10000
<random_state>:= 0 | 50 | 100